version: "3.9"

services:
  db:
    image: postgres:15
    container_name: biblioteca_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: biblioteca
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  mongodb:
    image: mongo:7
    container_name: biblioteca_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongo123
    ports:
      - "27017:27017"   # ⚠️ solo expón si necesitas acceder desde fuera
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  mongo-express:
    image: mongo-express
    container_name: biblioteca_mongo_express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo123
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - backend

  api:
    build: ./api
    container_name: biblioteca_api
    restart: always
    environment:
      DATABASE_URL: postgres://admin:admin123@db:5432/biblioteca
      MONGO_URL: mongodb://mongoadmin:mongo123@mongodb:27017/
    depends_on:
      - db
      - mongodb
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: biblioteca_nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    networks:
      - backend

volumes:
  postgres_data:
  mongo_data:

networks:
  backend:
